### ISSUE TITLE
[webUI] Unrelated properties are shown

### ISSUE THREAD

**Issue by kvndrsslr** [dice-group/deer#18]
<img width="398" alt="issue1" src="https://user-images.githubusercontent.com/46481738/117778514-ffd79600-b23d-11eb-81a7-62d4c6f5279f.png">

For some operators, unrelated properties are shown.
For example, `FileModelWriter` declares just two properties `fromUri` and `fromPath` but in the example above multiple unrelated properties are shown.

**Comment by pskLana** [comment]
Same as https://github.com/dice-group/deer/issues/20

**Comment by kvndrsslr** [comment]
This is *not* fixed.
FileModelReader is not supposed to have a selector property, however, this happens:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/46481738/124229463-f10ab280-db0d-11eb-8489-343092448f0a.png">

Then, with the above configuration, the following RDF is generated:

```
[Log] @prefix example: <urn:example:demo/>. (main.83535f34.chunk.js, line 1)
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix dbpedia: <http://dbpedia.org/resource/>.
@prefix deer: <https://w3id.org/deer/>.
@prefix fcage: <https://w3id.org/fcage/>.
@prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>.
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

example:test2 a deer:FileModelWriter;
    fcage:hasInput ([
  fcage:fromNode example:test;
  fcage:fromPort "0"^^xsd:integer
]);
    deer:outputFile "wurm.ttl".
example:test a deer:FileModelReader;
    deer:selector [ deer:fromPath <hello.ttl> ].
```

which is also incorrect (why is `deer:fromPath` wrapped in a `deer:selector here`? This is not part of the SHACL shape. I suspect your list parsing code has some bugs.)

**Comment by pskLana** [comment]
For me, everything is okay. Seems like you use an old version.
![image](https://user-images.githubusercontent.com/48616148/125198682-41e37f00-e263-11eb-953c-4ce741f03fd2.png)
The following rdf is generated for me:
```
@prefix example: <urn:example:demo/>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix dbpedia: <http://dbpedia.org/resource/>.
@prefix deer: <https://w3id.org/deer/>.
@prefix fcage: <https://w3id.org/fcage/>.
@prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>.
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

example:test a deer:FileModelReader;
    deer:fromPath "hello.ttl".
```

**Comment by kvndrsslr** [comment]
I tried again with the following:

In Terminal:
```bash
git checkout feature/webGUI
git pull
cd deer-web-ui
npm install
npm run build
cd ..
mvn clean package shade:shade -Dmaven.test.skip=true
java -jar deer-cli/target/deer-cli-2.3.2-SNAPSHOT.jar -s
```

In Browser:
- open `localhost:8080`
- create new node
- select FileModelReader

Result:

![image](https://user-images.githubusercontent.com/46481738/127139665-63188bbb-aaa5-4085-b32c-cb65b5c6d62c.png)


Please **triple check*** this. Do you have any local changes that aren't committed?

**Comment by kvndrsslr** [comment]
Fixed
