### ISSUE TITLE
[webUI] Files are not uploaded

### ISSUE THREAD

**Issue by kvndrsslr** [dice-group/deer#21]
<img width="527" alt="issue4" src="https://user-images.githubusercontent.com/46481738/117780424-e6cfe480-b23f-11eb-9304-0eff225c3788.png">

**Expected behaviour:** Users can select 0-N files to be uploaded alongside the configuration. There is no "Upload" button necessary.

**Actual behaviour:** Files can be selected but are not uploaded. An "Upload" button is displayed.

Tasks:
- [x] remove the upload button
- [x] upload files alongside the configuration file as part of a `multipart/form-data` request. The part name of the files must be set to their actual file names.

**Comment by pskLana** [comment]
@kvndrsslr , selected files should be uploaded when the run configuration button is clicked as I understood you. I didn't know which endpoint should I use, so I used "/upload". Check the implemented functionality and let me know whether it is what you expected.

**Comment by kvndrsslr** [comment]
The files should be sent as part of the same request as the configuration file, i.e. `/submit`.
