### ISSUE TITLE
[webUI] Status Polling does not stop after receiving error

### ISSUE THREAD

**Issue by kvndrsslr** [dice-group/deer#22]
<img width="918" alt="issue5" src="https://user-images.githubusercontent.com/46481738/117780355-d6b80500-b23f-11eb-9540-219063dbe1f5.png">

After receiving an error, polling for the job should stop since there are no more updates to be expected.

**Comment by pskLana** [comment]
@kvndrsslr , how to reproduce this bug?

**Comment by kvndrsslr** [comment]
try to load data from a file that does not exist, e.g. use a FileModelReader and input an arbitrary file name without providing that file.
